### ISSUE TITLE
Change name in right-click menu?

### ISSUE THREAD

**Issue by wanieru** [pappymint/named-pets-runelite#1]
Thanks for making this!

I'm wondering if it's possible to change the name of the pet in the right-click menu to whatever I've named it? :)

**Comment by pappymint** [comment]
Hi Wanieru,
Thank you for your suggestion! Would you be able to create a short video or some screenshots to exactly explain what kind of functionality you would like implemented?

**Comment by pappymint** [comment]
Hi, there is a new update to set the menu option name to your custom pet name. Please re-open this issue if I have misunderstood your request. Thanks!

**Comment by wanieru** [comment]
hi, sorry I never got back on this request - but yes that was exactly what I wanted! Thank you so much!
